baseURL = "https://blog.yamano.dev/"
languageCode = "ja-jp"
title = "/var/log/life"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = false

[services.googleAnalytics]
id = 'G-KP0FSYKJ50'

[params]
rss = "index.xml"
recent_posts_number = 10

[params.ananke.social.follow]
networks = [
  "rss",
  "x-twitter",
  "github",
]

[params.ananke.social.rss]
profilelink = "https://blog.yamano.dev/index.xml"

[params.ananke.social.x-twitter]
username = "yoshihisa_ya"

[params.ananke.social.github]
username = "yoshihisa-ya"

[permalinks]
posts = "/posts/:slug/"
